config/routes.rb
Rails.application.routes.draw do
  get "register", to: "users#new"
  post "register", to: "users#create"
  get "users", to: "users#show"
  delete "users/:id", to: "users#destroy", as: "delete_user"
  get "users/:id/edit", to: "users#edit", as: "edit_user"
  patch "users/:id", to: "users#update", as: "update_user"
  root "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    userInfo = params.require(:user).permit(:firstName, :lastName, :birthDay, :gender, :email, :phone, :subject)
    @user = User.new(userInfo)
    if @user.save
      redirect_to users_path
      # else
      #   render :new
      
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(params.require(:user).permit(:firstName, :lastName, :birthDay, :gender, :email, :phone, :subject))
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRegisterForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'new', media: 'all', 'data-turbolinks-track': 'reload' %>
<section class="center-content"</section>
  <%= form_with(model: @user, url: update_user_path, html: { class: 'user-form' }) do |form| %>
    <section class="back-button">
      <%= link_to '< Back', users_path, class: 'view-user-link' %>
    </section>
    <section class="header">
      <h1>Edit Form</h1>
    </section>
    <section class=two-column>
      <section class="left-column">
        <%= form.label :firstName, class: 'form-label' %>
        <%= form.text_field :firstName, class: 'form-control' %>
      </section>
      <section class="right-column">
        <%= form.label :lastName, class: 'form-label' %>
        <%= form.text_field :lastName, class: 'form-control' %>
      </section>
    </section>
    <section class=two-column>
      <section class="left-column">
        <%= form.label :birthDay, class: 'form-label' %>
        <%= form.date_field :birthDay, class: 'form-control' %>
      </section>
      <section class="right-column">
        <%= form.label :gender, "Gender", class: 'form-label' %>
        <section class="form-radio-group">
          <section class="radio-group">
            <%= form.radio_button :gender, "Male", class: 'form-radio' %>
            <%= form.label :gender, "Male", value: "Male", class: 'form-radio-label' %>
          </section>
          <section class="radio-group">
            <%= form.radio_button :gender, "Female", class: 'form-radio' %>
            <%= form.label :gender, "Female", value: "Female", class: 'form-radio-label' %>
          </section>
        </section>
      </section>
    </section>
    <section class=two-column>
      <section class="left-column">
        <%= form.label :email, class: 'form-label' %>
        <%= form.email_field :email, class: 'form-control' %>
      </section>
      <section class="right-column">
        <%= form.label :phone, class: 'form-label' %>
        <%= form.text_field :phone, class: 'form-control' %>
      </section>
    </section>
    <section class="one-column">
      <%= form.label :subject, class: 'form-label' %>
      <%= form.select :subject, options_for_select([["HTML"], ["CSS"], ["JavaScript"]], @user.subject), {}, { class: 'form-select' } %>
    </section>
    <section class="one-column">
      <%= form.submit "Update", class: 'form-submit' %>
    </section>
  <% end %>

app/views/users/new.html.erb
<%= stylesheet_link_tag 'new', media: 'all', 'data-turbolinks-track': 'reload' %>
<section class="center-content"</section>
  <%= form_with(model: @user, url: register_path, html: { class: 'user-form' }) do |form| %>
    <section class="back-button">
      <%= link_to '< Back', users_path, class: 'view-user-link' %>
    </section>
    <section class="header">
      <h1>Register Form</h1>
    </section>
    <section class=two-column>
      <section class="left-column">
        <%= form.label :firstName, class: 'form-label' %>
        <%= form.text_field :firstName, class: 'form-control' %>
      </section>
      <section class="right-column">
        <%= form.label :lastName, class: 'form-label' %>
        <%= form.text_field :lastName, class: 'form-control' %>
      </section>
    </section>
    <section class=two-column>
      <section class="left-column">
        <%= form.label :birthDay, class: 'form-label' %>
        <%= form.date_field :birthDay, class: 'form-control' %>
      </section>
      <section class="right-column">
        <%= form.label :gender, "Gender", class: 'form-label' %>
        <section class="form-radio-group">
          <section class="radio-group">
            <%= form.radio_button :gender, "Male", class: 'form-radio' %>
            <%= form.label :gender, "Male", value: "Male", class: 'form-radio-label' %>
          </section>
          <section class="radio-group">
            <%= form.radio_button :gender, "Female", class: 'form-radio' %>
            <%= form.label :gender, "Female", value: "Female", class: 'form-radio-label' %>
          </section>
        </section>
      </section>
    </section>
    <section class=two-column>
      <section class="left-column">
        <%= form.label :email, class: 'form-label' %>
        <%= form.email_field :email, class: 'form-control' %>
      </section>
      <section class="right-column">
        <%= form.label :phone, class: 'form-label' %>
        <%= form.text_field :phone, class: 'form-control' %>
      </section>
    </section>
    <section class="one-column">
      <%= form.label :subject, class: 'form-label' %>
      <%= form.select :subject, options_for_select([["HTML"], ["CSS"], ["JavaScript"]]), {}, { class: 'form-select' } %>
    </section>
    <section class="one-column">
      <%= form.submit "Create", class: 'form-submit' %>
    </section>
  <% end %>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'show', media: 'all', 'data-turbolinks-track': 'reload' %>
<section class="center-content">
  <section class="user-list" >
    <section class="header">
      <h1>User List</h1>
    </section>
    <%= link_to 'Create User', register_path, class: 'btn btn-create create-button' %>
    <section class="content">
      <% @users.each do |user| %>
        <div class="user-card">
          <div class="user-info">
            <p><strong>First Name:</strong> <%= user.firstName %></p>
            <p><strong>Last Name:</strong> <%= user.lastName %></p>
            <p><strong>Email:</strong> <%= user.email %></p>
          </div>
          <div class="button-row-layout">
            <%= link_to 'Edit', edit_user_path(user), class: 'btn btn-edit' %>
            <%= button_to 'Delete', delete_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-delete' %>
          </div>
        </div>
      <% end %>
    </section>
  </section>
</section>